services:
    mariadb:
        image: 'mariadb:latest'
        container_name: shop-backup-mariadb
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        ports:
            - '${DB_PORT:-3307}:3306'
    php-fpm:
        build: phpdocker/php-fpm
        container_name: shop-backup-php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/fpm/conf.d/99-overrides.ini'
